# Generated by Django 3.2.4 on 2021-10-15 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_uploadimagetest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimagetest',
            name='name',
        ),
        migrations.AddField(
            model_name='uploadimagetest',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.customuser'),
            preserve_default=False,
        ),
    ]
