# Generated by Django 3.2.4 on 2021-10-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20211015_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='profile_pics'),
        ),
    ]
