# Generated by Django 3.2.4 on 2021-10-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
