# Generated by Django 3.2.4 on 2021-10-13 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_auto_20211012_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='asigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.customuser'),
            preserve_default=False,
        ),
    ]
