# Generated by Django 3.2.4 on 2021-10-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_asigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
