# Generated by Django 3.2.4 on 2021-11-05 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20211105_0529'),
        ('myclub', '0003_post_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.profile')),
                ('post_commented', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myclub.post')),
            ],
        ),
    ]
