# Generated by Django 3.2.4 on 2021-11-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclub', '0004_coment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='comment',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
